### PR TITLE
Adds smoother support of framework for Java/Groovy users

### PR DESCRIPTION
**Pull request by ilya-ershov**
Effectively includes three features in priority order:
- Opens MockService and MockedUi classes to make clients code more DRY
- @JvmStatic and @JvmOverloads to support static-like method calling
- Adds UIFactory and ServiceFactory java interfaces to make `setup()` parameters look more naturally for Java/Groovy users

Everything except opening a few classes is optional for me.

### CODE REVIEW

**Comment by ilya-ershov** [comment]
You are right, no sense to do that partially and even if it eases life for Java users, it hardens life of Kotlin users. 
As I understant jetbrains intentially doesnt support kotlin interfaces as SAM. A. Breslav told that funtional types must be used instead.
Java wrapper would be cool for less experienced users to get started with library. However, for me its ok as it is now. Is there a chance that PR could be merged this week?

**Comment by mvysny** [comment]
I'm sick as hell right now and tomorrow I'm taking a flight which doesn't really help :) . But I'll try my best to merge tomorrow.
Too bad about Kotlin interfaces not being SAMs - would you happen to have a link to the discussion please?

**Comment by ilya-ershov** [comment]
Here I've found SOF discussion when faced the issue: https://stackoverflow.com/questions/33590646/kotlin-use-a-lambda-in-place-of-a-functional-interface
And that is the issue itself (just spotted it, it is already created)
https://youtrack.jetbrains.com/issue/KT-7770

**Comment by mvysny** [comment]
looks good to me :+1:

**Comment by ilya-ershov** [comment]
Thank you! Looking forward to have it released. Versions coming "karibu-testing-v10:0.4.15" and "mock-servlet-environment:0.4.15" ?

**Comment by mvysny** [comment]
Yup :+1: please confirm first that the API works for you and let me know.

**Comment by ilya-ershov** [comment]
I confirm, works as expected.

**Pull request merged**
